"""FastAPI + HTMX app for local SQL adapter queries."""

from __future__ import annotations

from jinja2 import DictLoader, Environment, select_autoescape

from sqlbench_lab.sql.serving import OpenAICompletionTransport
from sqlbench_lab.webapp.sql_query import SQLAskAppConfig, SQLAskQueryService


INDEX_TEMPLATE = """
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>SQL Ask</title>
  <script src="https://unpkg.com/htmx.org@2.0.4"></script>
  <style>
    :root {
      color-scheme: light;
      --bg: #f7f8fa;
      --ink: #172026;
      --muted: #5f6b76;
      --line: #d7dde3;
      --panel: #ffffff;
      --accent: #0f766e;
      --danger: #b42318;
      --code: #101828;
    }
    * { box-sizing: border-box; }
    body {
      margin: 0;
      background: var(--bg);
      color: var(--ink);
      font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      letter-spacing: 0;
    }
    main {
      width: min(1180px, calc(100vw - 32px));
      margin: 0 auto;
      padding: 28px 0 44px;
    }
    header {
      display: flex;
      align-items: flex-end;
      justify-content: space-between;
      gap: 24px;
      border-bottom: 1px solid var(--line);
      padding-bottom: 18px;
    }
    h1 {
      margin: 0;
      font-size: 28px;
      line-height: 1.15;
      font-weight: 720;
    }
    .meta {
      display: grid;
      gap: 4px;
      color: var(--muted);
      font-size: 13px;
      text-align: right;
      overflow-wrap: anywhere;
    }
    .workspace {
      display: grid;
      grid-template-columns: minmax(320px, 0.9fr) minmax(420px, 1.4fr);
      gap: 28px;
      padding-top: 28px;
      align-items: start;
    }
    form {
      background: var(--panel);
      border: 1px solid var(--line);
      border-radius: 8px;
      padding: 18px;
    }
    label {
      display: block;
      font-size: 13px;
      font-weight: 700;
      margin-bottom: 8px;
    }
    textarea {
      width: 100%;
      min-height: 180px;
      resize: vertical;
      border: 1px solid var(--line);
      border-radius: 6px;
      padding: 12px;
      font: inherit;
      line-height: 1.45;
      color: var(--ink);
      background: #fff;
    }
    button {
      margin-top: 12px;
      width: 100%;
      border: 0;
      border-radius: 6px;
      background: var(--accent);
      color: white;
      min-height: 42px;
      font-weight: 700;
      cursor: pointer;
    }
    button:hover { filter: brightness(0.94); }
    .hint {
      color: var(--muted);
      font-size: 13px;
      line-height: 1.45;
      margin-top: 12px;
    }
    #result {
      min-height: 320px;
      background: var(--panel);
      border: 1px solid var(--line);
      border-radius: 8px;
      padding: 18px;
    }
    .empty {
      color: var(--muted);
      min-height: 280px;
      display: grid;
      align-content: center;
      text-align: center;
    }
    .htmx-indicator { display: none; }
    .htmx-request .htmx-indicator { display: inline; }
    .htmx-request button { opacity: 0.72; }
    @media (max-width: 860px) {
      header, .workspace { display: block; }
      .meta { text-align: left; margin-top: 12px; }
      #result { margin-top: 18px; }
    }
  </style>
</head>
<body>
  <main>
    <header>
      <div>
        <h1>Local SQL Ask App</h1>
      </div>
      <div class="meta">
        <span>Endpoint: {{ config.openai_base_url }}</span>
        <span>Model: {{ config.openai_model }}</span>
        <span>DB: {{ config.db_path }}</span>
      </div>
    </header>
    <section class="workspace">
      <form hx-post="/query" hx-target="#result" hx-swap="innerHTML">
        <label for="question">Natural language query</label>
        <textarea id="question" name="question" required placeholder="Which product category has the highest completed-order revenue?"></textarea>
        <button type="submit">Run query <span class="htmx-indicator">...</span></button>
        <p class="hint">SQL is generated by the local adapter endpoint, then executed locally with read-only SELECT execution.</p>
      </form>
      <section id="result">
        <div class="empty">Ask a question to see generated SQL and returned rows.</div>
      </section>
    </section>
  </main>
</body>
</html>
"""

RESULT_TEMPLATE = """
<style>
  .status-row {
    display: flex;
    justify-content: space-between;
    gap: 16px;
    color: #5f6b76;
    font-size: 13px;
    margin-bottom: 14px;
  }
  .error {
    border-left: 4px solid #b42318;
    background: #fff4f2;
    color: #7a271a;
    padding: 12px;
    border-radius: 4px;
    margin: 12px 0;
    overflow-wrap: anywhere;
  }
  pre {
    margin: 0 0 14px;
    background: #101828;
    color: #f8fafc;
    padding: 14px;
    border-radius: 6px;
    overflow: auto;
    white-space: pre-wrap;
  }
  table {
    width: 100%;
    border-collapse: collapse;
    font-size: 14px;
  }
  th, td {
    border-bottom: 1px solid #d7dde3;
    padding: 9px 8px;
    text-align: left;
    vertical-align: top;
  }
  th {
    color: #172026;
    font-weight: 700;
    background: #f7f8fa;
  }
  .muted {
    color: #5f6b76;
    font-size: 13px;
  }
</style>
<div class="status-row">
  <span>{{ result.row_count }} row{{ "" if result.row_count == 1 else "s" }}{% if result.truncated %} shown, truncated at {{ result.row_limit }}{% endif %}</span>
  <span>{{ "%.3f"|format(result.latency_seconds) }}s</span>
</div>
{% if result.generated_sql %}
  <pre><code>{{ result.generated_sql }}</code></pre>
{% endif %}
{% if result.error %}
  <div class="error">{{ result.error }}</div>
{% elif result.columns %}
  <table>
    <thead>
      <tr>{% for column in result.columns %}<th>{{ column }}</th>{% endfor %}</tr>
    </thead>
    <tbody>
      {% for row in result.rows %}
      <tr>{% for value in row %}<td>{{ value }}</td>{% endfor %}</tr>
      {% endfor %}
    </tbody>
  </table>
{% else %}
  <p class="muted">The query completed without returned columns.</p>
{% endif %}
"""


def create_app(
    *,
    config: SQLAskAppConfig,
    transport: OpenAICompletionTransport | None = None,
):
    from fastapi import FastAPI, Form
    from fastapi.responses import HTMLResponse

    service = SQLAskQueryService(config, transport=transport)
    templates = Environment(
        loader=DictLoader({"index.html": INDEX_TEMPLATE, "result.html": RESULT_TEMPLATE}),
        autoescape=select_autoescape(("html",)),
    )
    app = FastAPI(title="SQLBench Local SQL Ask App")

    @app.get("/", response_class=HTMLResponse)
    def index() -> HTMLResponse:
        html = templates.get_template("index.html").render(config=service.config)
        return HTMLResponse(html)

    @app.post("/query", response_class=HTMLResponse)
    def query(question: str = Form(...)) -> HTMLResponse:
        result = service.ask(question)
        html = templates.get_template("result.html").render(result=result)
        return HTMLResponse(html)

    return app


def serve_query_app(
    *,
    config: SQLAskAppConfig,
    host: str,
    port: int,
) -> int:
    import uvicorn

    app = create_app(config=config)
    uvicorn.run(app, host=host, port=port)
    return 0
